using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

[RequireComponent(typeof(NavMeshAgent))]
public class SphereBehavior : MonoBehaviour
{
    [SerializeField] private Transform target;
    private NavMeshAgent agent;

    // Start is called before the first frame update
    void Start()
    {
        agent = GetComponent<NavMeshAgent>();
    }

    // Update is called once per frame
    void Update()
    {
        agent.SetDestination(target.position);
        
    }

    void OnTriggerEnter(Collider other){
    if(other.CompareTag("Player")){
        Debug.Log("Player was touched by the sphere.", other.gameObject);
    }
    }
}
